### ISSUE TITLE
TypeError: torch.FloatTensor is not a Module subclass

### ISSUE THREAD

**Issue by qingfengmingyue** [knazeri/edge-informed-sisr#1]
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    main(mode=1)
  File "/root/edge-informed-sisr/main.py", line 42, in main
    model = EdgeMatch(config)
  File "/root/edge-informed-sisr/src/edge_match.py", line 27, in __init__
    self.sr_model = SRModel(config).to(config.DEVICE)
  File "/root/edge-informed-sisr/src/models.py", line 179, in __init__
    self.add_module('scale_kernel', kernel_weight)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 179, in add_module
    torch.typename(module)))
TypeError: torch.FloatTensor is not a Module subclass

**Comment by Dayananda-V** [comment]
@qingfengmingyue 

i found the working fix, please add the below code will fix this problem(just comment the add_module for scale_kernel instead create scale_kernel variable).

`#self.add_module('scale_kernel', kernel_weight)
self.scale_kernel = torch.tensor(np.tile(kernel, (3, 1, 1, 1))).float()`

**Comment by jsjs0827** [comment]
@Dayananda-V Can you show the result? I just figure out the mosaic.
