### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by ghzmwhdk777** [knazeri/edge-informed-sisr#11]
start training...

Training epoch: 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "train.py", line 2, in <module>
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\spawn.py", line 105, in spawn_main
    main(mode=1)
  File "D:\SR\edge-informed-sisr-master\main.py", line 50, in main
    exitcode = _main(fd)
    model.train()
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\spawn.py", line 114, in _main
  File "D:\SR\edge-informed-sisr-master\src\edge_match.py", line 95, in train
    prepare(preparation_data)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\spawn.py", line 225, in prepare
    for items in train_loader:
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\runpy.py", line 263, in run_path
    return self._get_iterator()
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\runpy.py", line 85, in _run_code
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    exec(code, run_globals)
  File "D:\SR\edge-informed-sisr-master\train.py", line 2, in <module>
    w.start()
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\process.py", line 112, in start
    main(mode=1)
  File "D:\SR\edge-informed-sisr-master\main.py", line 50, in main
    model.train()
  File "D:\SR\edge-informed-sisr-master\src\edge_match.py", line 95, in train
    for items in train_loader:
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
    self._popen = self._Popen(self)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\context.py", line 223, in _Popen
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\context.py", line 322, in _Popen
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
    return Popen(process_obj)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
    reduction.dump(process_obj, to_child)
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\reduction.py", line 60, in dump
    _check_not_importing_main()
  File "C:\Users\SYM\AppData\Local\conda\conda\envs\deepcamp\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe

------------------------------------------------------------
what is wrong with me? i cant find any solution

**Comment by ghzmwhdk777** [comment]
sloved
